services:
    redmine.connection:
        class: RedmineBundle\Connection
        arguments: ['%redmine_url%', '%redmine_api_key%']

    redmine.api_helper:
        class: RedmineBundle\ApiHelper
        arguments: ['@redmine.connection']
