<?php

namespace RedmineBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $projectId
     * @return \Doctrine\ORM\Query
     */
    public function getCommentsByProject(int $projectId)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.projectId = :projectId')
            ->setParameter('projectId', $projectId)
            ->getQuery();
    }
}
