<?php

namespace RedmineBundle\Repository;

/**
 * TrackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerRepository extends \Doctrine\ORM\EntityRepository
{
}
